### ISSUE TITLE
kdtreeを用いてmainの計算を行うにあたっていくつか質問

### ISSUE THREAD

**Issue by KishiShohei** [Enehentaro/droplets_simulation#126]
①kdTree.f90とunstructuredGrid.f90はそれぞれ別のファイルとして置いておきますか？それともunstructuredGrid.f90内にkdTree.f90の内容を加え、kdTree.f90は削除しますか？今現在(kdTreeブランチ)は、前者になっています。
②「静止格子の場合、kdtreeの構築は1回で良いはず。なので、最初の計算でvtkディレクトリ下に、逆探索に必要な情報をkdTree.txtとして出力する(ここまでは既に出来ている)。2回目以降の計算ではkdTree.txtファイルを読み込んでnearest_cellの探索を行う。」というようにするのが良いかなと思っていますがどうでしょう？
③2回目以降の計算で、unstructuredGrid.f90内のサブルーチンsetup_kdTreeでkdtree.txtを読み込む。そして、nearest_cell関数で逆探索を行おうと思っていますが上手くいきません。どうやら、サブルーチンsetup_kdTreeで読み込み&保持した情報が、nearest_cell関数で逆探索を行う際には消えているようです。nearest_cell関数内でtxt読み込み&逆探索を行えば上手くいくとは思いますが、ほかに何か良い方法はありますでしょうか...？

**Comment by Tauzu** [comment]
1. ファイルは分けておきましょう
2. それでよいとおもいます
3. 読み込んだ情報は、UnstructuedGridクラス内のメンバ変数に格納する必要があると思う

**Comment by KishiShohei** [comment]
おけです。

**Comment by KishiShohei** [comment]
一応僕の環境ではmainで計算できるようになったので、確認してみてください。kdTree.f90のkdTreeクラスのprivate変数があるとエラーが出てしまうので、一時的に外していますが、あまりよくないですよね...？

**Comment by Enehentaro** [comment]
https://github.com/Enehentaro/droplets_simulation/commit/e27bc2d35e24bf22958a53fb9daaa4c7d4e37e59
コメントしました。

**Comment by KishiShohei** [comment]
[5ae359a](https://github.com/Enehentaro/droplets_simulation/commit/5ae359a871c54cff7c0fb230943ce677dc816605)
修正しました。こんな感じで大丈夫ですかね？

**Comment by Tauzu** [comment]
多分OK
回れば

**Comment by Tauzu** [comment]
要素数が一万ぐらいになると、ヒープソートの所要時間が急増するのはなぜなんだろう？

**Comment by Tauzu** [comment]
↑解決しました。
プルリク出しました。

**Comment by KishiShohei** [comment]
承認しました。あと、以前kdTree.f90のサブルーチンread_kdTreeの引数に含んでいたセル数を削除しました。
b19bbb067798c66e7f6b8307a8f61f12f42948c5

**Comment by mochimochikun** [comment]
https://15.gigafile.nu/0802-d4173cd6812a1ca5cd1fa460c4f57a38

**Comment by KishiShohei** [comment]
↑のファイルでエラーが出るので修正してみます。

**Comment by KishiShohei** [comment]
fed6b4c135cace5a95d29d0b079056f017397596
自分の気道モデルのやつとかでも回してみましたが、格子数200万を超えると、Segmentation faultになるようです。

**Comment by Tauzu** [comment]
そこループ内だけど、ループの1回目でエラーになる？

**Comment by KishiShohei** [comment]
![スクリーンショット (15)](https://user-images.githubusercontent.com/87518019/180961940-7b9e9114-cf37-4813-8894-f2780844d628.png)
そうですね。CREATING kd-treeが1のときにエラーが出ます。

**Comment by Tauzu** [comment]
シンプルにメモリ上限エラーかなあ。
![image](https://user-images.githubusercontent.com/87505664/180963700-5601ce16-9e57-477c-a4e5-8fae2879ec81.png)
↑のようにオプション書き換えてビルドやり直してみて

**Comment by KishiShohei** [comment]
書き直してもう一回やってみましたが、やはりSegmentation faultになります...格子数10万とかでは通るのに、200万に増えると通らないとなると、メモリの可能性が高そうですね...

**Comment by KishiShohei** [comment]
![スクリーンショット (16)](https://user-images.githubusercontent.com/87518019/180967304-7cad8288-6cd1-4341-b39d-bde3b9d64bc7.png)
関係あるか分かりませんが、上記のようにarray_preを変えるとsort.f90でSegmentation faultになりました。

**Comment by Tauzu** [comment]
あー、`(:)`は配列のスライスだから、ロジックが変わるね。
allocateされてない配列にスライスしても何も起こらない。

**Comment by Tauzu** [comment]
こちらの環境では、エラーにはならず、CREATING kd-treeの1でずっとがんばってます

**Comment by KishiShohei** [comment]
8772a117b3ed88016d121560456dc9a783904b24
もともとx_origin(kdTree_%node(i)%cellID_array)としてx_originに格納してましたが、ここでSegmentationエラーになって格納できていなかったようでした(なぜかは不明)。なので、あまり良くないかもしれないですが、書き方を変えてみました。変更後に計算を回してみたところ、セグメンテーションエラーはなくなりましたが、井田さんと同じくCREATING kd-treeの1で計算が終わりません。

**Comment by KishiShohei** [comment]
![Screenshot from 2022-08-09 12-35-04](https://user-images.githubusercontent.com/87518019/183558615-b109f489-8853-42ed-bb72-2ff6cec721d5.png)
気道のfldで飛沫計算(kd-tree)回してたら、adjacentCellArrayのとこでエラーが出ました。この辺見たことないので、なにかコメント頂けると幸いです。
fldは以下のリンクからダウンロードできます。
https://33.gigafile.nu/1117-88fdfc0661a38177e6b64bf8e52eded6

**Comment by Tauzu** [comment]
確認したくないです。自力でがんば。

エラー文から察すると、
配列サイズ外アクセスしちゃってるので、
隣接セルが想定の4個を超えて5個発見されちゃってる。

オールテトラ格子か、プリズム有りかわからんが、プリズムには対応させたつもりなので原因不明。
もし謎の多面体使ってるなら未対応なので自力実装よろ。

**Comment by KishiShohei** [comment]
おけです

**Comment by KishiShohei** [comment]
コンパイルオプション切ったら上手くいったので、まあ大丈夫だと思います。

**Comment by Tauzu** [comment]
> コンパイルオプション`-warn all -check all`切ったら上手くいったので、まあ大丈夫だと思います。

謎すぎ


> ソート遅い問題は解決しましたが、txt出力であほみたいに時間かかるので、改善しときます。

どうやって解決したんすか？

**Comment by KishiShohei** [comment]
ヒープソートの代わりに、マージソートを導入してみました。一応テストしてみて、上手くいってはいると思います。ただ、c言語のサンプルコードを参考に書いただけなので、アルゴリズムの詳しいところはこれから勉強することになりそうです。(メモリがちょっと心配なので)

**Comment by KishiShohei** [comment]
気が向いたら直します
