### ISSUE TITLE
薬ってなんやねん

### ISSUE THREAD

**Issue by KishiShohei** [Enehentaro/droplets_simulation#135]
薬の場合、蒸発、合体、死滅は考慮しないのか？
死滅計算はコード見た感じ、現在はやってなさそう。合体判定は0で良いとして、蒸発はどうするべきか。
optionで切り替えられるようにするのがよさそう？

**Comment by Tauzu** [comment]
死滅は今もやってるはず（`DropletGroup`の`survival_check`メソッド）。
粉薬なら蒸発はしないだろうね。
~粉末同士の反発は・・・~

**Comment by KishiShohei** [comment]
おけですw

**Comment by KishiShohei** [comment]
c8df5798cea455ff09675dc2a37e97ca94da27cc
蒸発計算と死滅計算の切り替えをbasicSetting.nmlから変えられるようにしました。
ONの場合とOFFの場合のvtkの直径を見比べた感じ、上手く行ってそうな気がしますが不安です。気が向いたらで良いので確認してもらえると助かります。
あとvtkを見た感じ、付着した飛沫の最終飛沫直径は0にしているように見えますが、合っているでしょうか？

**Comment by Tauzu** [comment]
わざわざスイッチ作ったんかいｗ
まあいけてるんじゃね

> あとvtkを見た感じ、付着した飛沫の最終飛沫直径は0にしているように見えますが、合っているでしょうか？

そんな処理はしてないと思うんだが・・・。合体飛沫の片方は直径ゼロにしたけど。

**Comment by KishiShohei** [comment]
飛沫直径の件、分かりました。
あと、なぜか死滅計算も蒸発計算も両方trueなのに、飛沫の挙動が他のブランチ(cmakeとか)の計算結果と比べて変になっているので、修正します。

**Comment by KishiShohei** [comment]
すみません、cmakeの方で回していた計算が咳の飛沫半径で行っていました💦
cmakeの方でも、薬の飛沫半径で回してみたら、Kishi_medと同じような飛沫の挙動になったので、大丈夫かと思います。
確かに今作業しているブランチが割と古いので、cmakeとマージした方が良さそうですね。

**Comment by KishiShohei** [comment]
解決済み
