### ISSUE TITLE
developブランチ要らんのちゃう

### ISSUE THREAD

**Issue by Tauzu** [Enehentaro/droplets_simulation#138]
developブランチの存在価値がもはやない気がするので、masterにマージしたあと削除するのがよいと思いますがどうでしょう？
最終判断は岸君に委ねます

**Comment by KishiShohei** [comment]
おけです、今度やっときます。

**Comment by KishiShohei** [comment]
settingsタブが無いので、developブランチの鍵を外せないです。マージは既に済んでいるので、消してもらえますか？

**Comment by Tauzu** [comment]
エネヘン太郎アカウントでログインすれば管理者権限で外せるはず

**Comment by Enehentaro** [comment]
消せました。

**Comment by Enehentaro** [comment]
おわり
