### ISSUE TITLE
初期の飛沫配置数が多すぎるとセグメンテーション違反が発生する

### ISSUE THREAD

**Issue by mochimochikun** [Enehentaro/droplets_simulation#95]
今は1分間とか咳1回分とかでしか計算していないため大体飛沫配置数は1万個だが，
例えば1時間分計算したいとなると1分で咳1回とすると飛沫配置数は60万個になる．
しかし，飛沫配置数を60万個にしてプログラムを実行すると**セグメンテーション違反**となる．

何か解決策はないでしょうか？

**Comment by KishiShohei** [comment]
これもいらないよね？
